#!/bin/sh
r='Wed, 1 Jan 2020 22:51:53 GMT'
d=$(date -d "$r" -D "%a, %d %b %Y %T %Z" +'%Y-%m-%d %H:%M:%S')
# d becomes 2019-01-15 09:01:53
date -s "$d"
alsactl --file /root/asound.state restore
swapon /dev/mmcbkl0p3 || `mkswap /dev/mmcblk0p3; swapon /dev/mmcblk0p3`

